server:
  address: 0.0.0.0
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: runhome
  config:
    import: "optional:file:./.env[.properties]"
  datasource:
    url: jdbc:mysql://${MYSQLHOST:${DB_HOST:localhost}}:${MYSQLPORT:3306}/${MYSQLDATABASE:runhome}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER:${DB_USERNAME:root}}
    password: ${MYSQLPASSWORD:${DB_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    "[com.l2kb.runhome]": INFO
    "[org.springframework.web]": WARN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
